### ISSUE TITLE
Review - Validation

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_drought#100]
What scores do you plan to use and why? Do you only want to use shap values? If yes, why?

**Comment by gabrieltseng** [comment]
We are currently using [RMSE](https://github.com/esowc/ml_drought/blob/master/src/models/base.py#L124) and [R^2](https://github.com/esowc/ml_drought/blob/master/notebooks/draft/09_gt_r2.ipynb) to measure the distance between our predictions and the true VHI values. These are relatively standard metrics in the field of machine learning (and indeed climate science).

We use R^2 because this is the metric used by drought monitoring authorities in Kenya when validating the models they currently use in production.

Shap values are not necessarily used for quantitative validation, rather they are used to interpret feature importance.

**Comment by cvitolo** [comment]
That's very clear, many thanks! Closing this issue now.
