### ISSUE TITLE
Review - Feature selection

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_drought#98]
- You initially requested a large variety of data. Could you please give details of feature selection? What variables did you decide to use and why did you not use the others?

- It would also be great to have a look-up table to link variable name as used by the CDS/MARS and the variable name used in your notebooks.

**Comment by tommylees112** [comment]
> `You initially requested a large variety of data. Could you please give details of feature selection? What variables did you decide to use and why did you not use the others?`

We are currently using `[precipitation, VHI, evaporation, soil moisture, temperature]` to predict `VHI`. The current data are from different sources including [CHIRPS for precipitation](https://www.nature.com/articles/sdata201566) and [GLEAM for soil moisture / evaporation](https://www.gleam.eu/) because of export times. We are downloading alternative data from ERA5 (temperature, evaporation). 

Feature selection can be done using Shapley values to test the relative contribution of each variable to the pixel prediction. 

> `It would also be great to have a look-up table to link variable name as used by the CDS/MARS and the variable name used in your notebooks.`

The variable names should be the same since the parameter `variable` has the same name as the call to the `cdsapi` when you build a request using the [CDS Website](https://cds.climate.copernicus.eu/#!/home).

The variables with non-standard names (e.g. VHI) are likely from alternative data sources.
